version: '3'
services:

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"

  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb
    ports:
      - "6543:5432"

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - "3306:3306"
